{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin",
    "version": "0.10.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-0.10.1-SNAPSHOT.jar",
          "url": "gr8-plugin-0.10.1-SNAPSHOT.jar",
          "size": 6826781,
          "sha512": "6e9416d2ef8f033704af119e1489d44887e5409a9608bcef0b93b587631d7c808781bb7b73409a94388ca49671bb6c18f5a09d3527f329d8b3372a1800723ea5",
          "sha256": "3a4b77e2ac7d279fd97afad238e4845893bb0264d3f84834f7603adcdf12c91b",
          "sha1": "ba09e73772a9b6676bab6c1207fb88f1ac5967c1",
          "md5": "ceb83a1e4c706ef52c171c89bb457777"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup",
          "module": "gr8-plugin-common",
          "version": {
            "requires": "0.10.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-0.10.1-SNAPSHOT.jar",
          "url": "gr8-plugin-0.10.1-SNAPSHOT.jar",
          "size": 6826781,
          "sha512": "6e9416d2ef8f033704af119e1489d44887e5409a9608bcef0b93b587631d7c808781bb7b73409a94388ca49671bb6c18f5a09d3527f329d8b3372a1800723ea5",
          "sha256": "3a4b77e2ac7d279fd97afad238e4845893bb0264d3f84834f7603adcdf12c91b",
          "sha1": "ba09e73772a9b6676bab6c1207fb88f1ac5967c1",
          "md5": "ceb83a1e4c706ef52c171c89bb457777"
        }
      ]
    }
  ]
}
