{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-external",
    "version": "0.11.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.2-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.2-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "ab902d5c36f1e905a1c38582d9a06fb569162c8c5354960e5b5ce6378975e9609c56780fb840a83266483dc45c0dc79e99c5bd0c43d13fea25769a5a887de3d8",
          "sha256": "2c4aa7a4f9d8b82ed17571d1180045b7089ed7508ab18007005b114b0803245f",
          "sha1": "3526aa89e6c1aa2970121fb4823e284b4e7f1bd8",
          "md5": "0787089db9513b72ddb8bdc45b060897"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup",
          "module": "gr8-plugin-common",
          "version": {
            "requires": "0.11.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.2-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.2-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "ab902d5c36f1e905a1c38582d9a06fb569162c8c5354960e5b5ce6378975e9609c56780fb840a83266483dc45c0dc79e99c5bd0c43d13fea25769a5a887de3d8",
          "sha256": "2c4aa7a4f9d8b82ed17571d1180045b7089ed7508ab18007005b114b0803245f",
          "sha1": "3526aa89e6c1aa2970121fb4823e284b4e7f1bd8",
          "md5": "0787089db9513b72ddb8bdc45b060897"
        }
      ]
    }
  ]
}
