{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-external",
    "version": "0.11.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.1-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.1-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "ac2dbd643ddc714fbe649237ca2429fb9aa5894345d08296f0c847f95c6f04a35ea0249c2bb6630ad37060b11b1a587bbefe75ff94d1fc8e7d4751650a8d361d",
          "sha256": "67fcf786e5a4fc530f583f1792b0983d9d67e5e6819b5a88081d4eac718eaa57",
          "sha1": "dc9b126a9830f0270b9be8d37ef855c307c77c29",
          "md5": "9d4a8d1c1a72c7cf655c2b93a388665a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup",
          "module": "gr8-plugin-common",
          "version": {
            "requires": "0.11.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.1-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.1-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "ac2dbd643ddc714fbe649237ca2429fb9aa5894345d08296f0c847f95c6f04a35ea0249c2bb6630ad37060b11b1a587bbefe75ff94d1fc8e7d4751650a8d361d",
          "sha256": "67fcf786e5a4fc530f583f1792b0983d9d67e5e6819b5a88081d4eac718eaa57",
          "sha1": "dc9b126a9830f0270b9be8d37ef855c307c77c29",
          "md5": "9d4a8d1c1a72c7cf655c2b93a388665a"
        }
      ]
    }
  ]
}
