{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-external",
    "version": "0.11.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.1-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.1-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "51a4d732373cd8e186c1e4baf1ce997e46f1ae8bbd1f9ce3ac16161a44285be0fdf7913a302678666f0dcfc415c6879149a18556270540c07294a244e6624b3c",
          "sha256": "33b47a10a34c7767e3213a15ab144d811a94878674722d59dc35d627f8f25fe8",
          "sha1": "8f6dde148f54fe12060236e7009d71c80e1c4fed",
          "md5": "827114f9a20c6319e4573b87f07196b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup",
          "module": "gr8-plugin-common",
          "version": {
            "requires": "0.11.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.1-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.1-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "51a4d732373cd8e186c1e4baf1ce997e46f1ae8bbd1f9ce3ac16161a44285be0fdf7913a302678666f0dcfc415c6879149a18556270540c07294a244e6624b3c",
          "sha256": "33b47a10a34c7767e3213a15ab144d811a94878674722d59dc35d627f8f25fe8",
          "sha1": "8f6dde148f54fe12060236e7009d71c80e1c4fed",
          "md5": "827114f9a20c6319e4573b87f07196b7"
        }
      ]
    }
  ]
}
