{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-common",
    "version": "0.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-common-0.11.1.jar",
          "url": "gr8-plugin-common-0.11.1.jar",
          "size": 34589,
          "sha512": "18665f2805c50f7b16b53da08aeaa10133059681626ebf6dfb40093250a55678deba343d4477d81543fab13b5a98131db335e0c8bd1c245c8e8583fcf674debe",
          "sha256": "10064134dc9b569450c6b701ffdbd86b2c5f8ce9d50f9a300bb4b8e5119a6044",
          "sha1": "d0c64ee43bd6559dedaa49dc11e36c0aeb964372",
          "md5": "86384e2ce4f6f75de9fda4666b0f087d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-common-0.11.1.jar",
          "url": "gr8-plugin-common-0.11.1.jar",
          "size": 34589,
          "sha512": "18665f2805c50f7b16b53da08aeaa10133059681626ebf6dfb40093250a55678deba343d4477d81543fab13b5a98131db335e0c8bd1c245c8e8583fcf674debe",
          "sha256": "10064134dc9b569450c6b701ffdbd86b2c5f8ce9d50f9a300bb4b8e5119a6044",
          "sha1": "d0c64ee43bd6559dedaa49dc11e36c0aeb964372",
          "md5": "86384e2ce4f6f75de9fda4666b0f087d"
        }
      ]
    }
  ]
}
