{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-external",
    "version": "0.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.1.jar",
          "url": "gr8-plugin-external-0.11.1.jar",
          "size": 2052,
          "sha512": "6f196e4a52d2db3e9f0046e778f67e0ec7fa8dec5dd0d57332ec9b587bed496e4e4a8da3ec2df13b9c48e5706ea7c2e050aeed1f10e1d2fc860e857d2f5d4cda",
          "sha256": "92ffb92e183b6f5c22019bf6d325ef97c056877fde5c0f86ca839ef6161929d1",
          "sha1": "1fb0b617ad938bafe54a12be5bac7b560709a88e",
          "md5": "1e17611bbef5f53706cded30d3873128"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup",
          "module": "gr8-plugin-common",
          "version": {
            "requires": "0.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.1.jar",
          "url": "gr8-plugin-external-0.11.1.jar",
          "size": 2052,
          "sha512": "6f196e4a52d2db3e9f0046e778f67e0ec7fa8dec5dd0d57332ec9b587bed496e4e4a8da3ec2df13b9c48e5706ea7c2e050aeed1f10e1d2fc860e857d2f5d4cda",
          "sha256": "92ffb92e183b6f5c22019bf6d325ef97c056877fde5c0f86ca839ef6161929d1",
          "sha1": "1fb0b617ad938bafe54a12be5bac7b560709a88e",
          "md5": "1e17611bbef5f53706cded30d3873128"
        }
      ]
    }
  ]
}
