{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-common",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-common-0.11.0.jar",
          "url": "gr8-plugin-common-0.11.0.jar",
          "size": 34591,
          "sha512": "89558b8d295d1c88f00c8bb7313af3ddc33fec48051e181285764a88e7064f4e7ff4fd6d2d6efb393490b635f1b87450a48efb197ea0100f95c29630d74f573e",
          "sha256": "456be0640002cf53a648b9852986831d1aac0b0b83802f9121b43bc7a743314d",
          "sha1": "55c8c5c5c2ac2553ac90f36059bdcee93a0ace93",
          "md5": "dd58e46f62d7ff35b1b703e365d3aa94"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "r8",
          "version": {
            "requires": "8.5.35"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-common-0.11.0.jar",
          "url": "gr8-plugin-common-0.11.0.jar",
          "size": 34591,
          "sha512": "89558b8d295d1c88f00c8bb7313af3ddc33fec48051e181285764a88e7064f4e7ff4fd6d2d6efb393490b635f1b87450a48efb197ea0100f95c29630d74f573e",
          "sha256": "456be0640002cf53a648b9852986831d1aac0b0b83802f9121b43bc7a743314d",
          "sha1": "55c8c5c5c2ac2553ac90f36059bdcee93a0ace93",
          "md5": "dd58e46f62d7ff35b1b703e365d3aa94"
        }
      ]
    }
  ]
}
