{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-external",
    "version": "0.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.0-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.0-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "7632460afa4d47fceeb3f369872f2dd6dcb60f4bec9766cb0669219317e92cc83e46764baf50cc9248ab0266cafa320ae491a55e67cc1d0fe14a2a47aa1c4505",
          "sha256": "58fefa2dba91178f9ce0859de10c2735ee366e191f92760f769558c94a7db7c0",
          "sha1": "bdf6685bb77b6da6f6ba1255724aea06ffab20a1",
          "md5": "4438df88f8e2512b878dbaa0cac9110d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup",
          "module": "gr8-plugin-common",
          "version": {
            "requires": "0.11.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.0-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.0-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "7632460afa4d47fceeb3f369872f2dd6dcb60f4bec9766cb0669219317e92cc83e46764baf50cc9248ab0266cafa320ae491a55e67cc1d0fe14a2a47aa1c4505",
          "sha256": "58fefa2dba91178f9ce0859de10c2735ee366e191f92760f769558c94a7db7c0",
          "sha1": "bdf6685bb77b6da6f6ba1255724aea06ffab20a1",
          "md5": "4438df88f8e2512b878dbaa0cac9110d"
        }
      ]
    }
  ]
}
