{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-external",
    "version": "0.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.0-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.0-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "8791a87ed42627b9a1a1f73808a41d43e9e19d3d28a9310cbdeced891e261425bad1f0f8566a6bc0257188e8086f3839d30daa2df865f43157568bc5cfd9899f",
          "sha256": "035323f073ff18d9f115ff7ce8c5ca6346cd8b38b42eba51499407e6623975db",
          "sha1": "ce90d7ad1e13cf546f5f4b99e5e8d7e5388aeee2",
          "md5": "04e00efeb1580efd7c93aadc3905d369"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup",
          "module": "gr8-plugin-common",
          "version": {
            "requires": "0.11.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.0-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.0-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "8791a87ed42627b9a1a1f73808a41d43e9e19d3d28a9310cbdeced891e261425bad1f0f8566a6bc0257188e8086f3839d30daa2df865f43157568bc5cfd9899f",
          "sha256": "035323f073ff18d9f115ff7ce8c5ca6346cd8b38b42eba51499407e6623975db",
          "sha1": "ce90d7ad1e13cf546f5f4b99e5e8d7e5388aeee2",
          "md5": "04e00efeb1580efd7c93aadc3905d369"
        }
      ]
    }
  ]
}
