{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-external",
    "version": "0.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.0-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.0-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "9393349d59f3bc573dd108552688ec55e0585e355c0647f6215ec937f5f42f19c87049734d25a84afa079aa22d0e1bfe146f0c7210c1b921f5854ddf459aea26",
          "sha256": "1e6c1dc7121ab57f707cdfcba2f38a16cabe42b0796270a67f980d59b9c4d647",
          "sha1": "bf9c927b48a746450ede64f0ef52aad010cd08ac",
          "md5": "7b01847313ab0c5bc23038a046eed3fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup",
          "module": "gr8-plugin-common",
          "version": {
            "requires": "0.11.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.0-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.0-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "9393349d59f3bc573dd108552688ec55e0585e355c0647f6215ec937f5f42f19c87049734d25a84afa079aa22d0e1bfe146f0c7210c1b921f5854ddf459aea26",
          "sha256": "1e6c1dc7121ab57f707cdfcba2f38a16cabe42b0796270a67f980d59b9c4d647",
          "sha1": "bf9c927b48a746450ede64f0ef52aad010cd08ac",
          "md5": "7b01847313ab0c5bc23038a046eed3fe"
        }
      ]
    }
  ]
}
