{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin",
    "version": "0.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-0.11.1.jar",
          "url": "gr8-plugin-0.11.1.jar",
          "size": 295756,
          "sha512": "36da5786d90db527d9d5b32dd56cd193a6bbf2b29d546e23a873ca03ccacb069b3101d9fff6eb7296590ceeae79c8137ce0e910b54b32b76220de61f65315d3d",
          "sha256": "47d447a937340681d98838e18e2bad445f8b72796c3c2c54f8d3b1b1a709a206",
          "sha1": "ef5997e78d6f5d1da3e8b2125d6dad45974a392e",
          "md5": "970be353f97a75e4905fe844393198c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup",
          "module": "gr8-plugin-common",
          "version": {
            "requires": "0.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-0.11.1.jar",
          "url": "gr8-plugin-0.11.1.jar",
          "size": 295756,
          "sha512": "36da5786d90db527d9d5b32dd56cd193a6bbf2b29d546e23a873ca03ccacb069b3101d9fff6eb7296590ceeae79c8137ce0e910b54b32b76220de61f65315d3d",
          "sha256": "47d447a937340681d98838e18e2bad445f8b72796c3c2c54f8d3b1b1a709a206",
          "sha1": "ef5997e78d6f5d1da3e8b2125d6dad45974a392e",
          "md5": "970be353f97a75e4905fe844393198c5"
        }
      ]
    }
  ]
}
