{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-common",
    "version": "0.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-common-0.11.0-SNAPSHOT.jar",
          "url": "gr8-plugin-common-0.11.0-SNAPSHOT.jar",
          "size": 34591,
          "sha512": "451fe12cbd9127c2eaef73a5e9392fd25d13b8f98a692539713335b2042db17e76b59530e8633cd7165df4bc51eba4ffc0a8ff7497bcadd60dc9a51eef98ee02",
          "sha256": "4f21187522e7d2b5df7f48e353a054398898f9b8ba457c13f000d3e5ac4548f7",
          "sha1": "6b88b5bb2c2b5ee2412e0d4f2dd9ce3e12c5e433",
          "md5": "13824d84e09b263b3d4e33c3030d28f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "r8",
          "version": {
            "requires": "8.5.35"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-common-0.11.0-SNAPSHOT.jar",
          "url": "gr8-plugin-common-0.11.0-SNAPSHOT.jar",
          "size": 34591,
          "sha512": "451fe12cbd9127c2eaef73a5e9392fd25d13b8f98a692539713335b2042db17e76b59530e8633cd7165df4bc51eba4ffc0a8ff7497bcadd60dc9a51eef98ee02",
          "sha256": "4f21187522e7d2b5df7f48e353a054398898f9b8ba457c13f000d3e5ac4548f7",
          "sha1": "6b88b5bb2c2b5ee2412e0d4f2dd9ce3e12c5e433",
          "md5": "13824d84e09b263b3d4e33c3030d28f4"
        }
      ]
    }
  ]
}
