{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin",
    "version": "0.11.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-0.11.1-SNAPSHOT.jar",
          "url": "gr8-plugin-0.11.1-SNAPSHOT.jar",
          "size": 6823301,
          "sha512": "06dfad19a42df0bf0a7c08b8dd53c59cd5263a3c90975f34f916f943088167d901e83715e69ae62b88cb5b7fc4fb703029d60a3209461c4c02691e0bd2279716",
          "sha256": "0d1ae4900d0e79fd3c22e793e57961441472ce92357fe615821cbd00cd9dab24",
          "sha1": "3004498f5936ced658136ea2d28109737c21c8e4",
          "md5": "4ac0f84c60f8991129399fa13ba02c72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup",
          "module": "gr8-plugin-common",
          "version": {
            "requires": "0.11.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-0.11.1-SNAPSHOT.jar",
          "url": "gr8-plugin-0.11.1-SNAPSHOT.jar",
          "size": 6823301,
          "sha512": "06dfad19a42df0bf0a7c08b8dd53c59cd5263a3c90975f34f916f943088167d901e83715e69ae62b88cb5b7fc4fb703029d60a3209461c4c02691e0bd2279716",
          "sha256": "0d1ae4900d0e79fd3c22e793e57961441472ce92357fe615821cbd00cd9dab24",
          "sha1": "3004498f5936ced658136ea2d28109737c21c8e4",
          "md5": "4ac0f84c60f8991129399fa13ba02c72"
        }
      ]
    }
  ]
}
