{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-external",
    "version": "0.11.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "ce94589fc326468ad036c9e73cede786d61c19d886bb4249840e14087c2ab1dcb0ad24bd49a5d6e4a029f1ea83a7030827158a25a9f056ca04769f4adec2a89a",
          "sha256": "e7a3fdb1fb8b05633d1132ae90fd8b4940018245ea029fc9a01c30c1fa21e002",
          "sha1": "e2e13f413354170952cea412748fcccd1a3d26b4",
          "md5": "5cee75000ae754e5f192083009e32279"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup",
          "module": "gr8-plugin-common",
          "version": {
            "requires": "0.11.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "ce94589fc326468ad036c9e73cede786d61c19d886bb4249840e14087c2ab1dcb0ad24bd49a5d6e4a029f1ea83a7030827158a25a9f056ca04769f4adec2a89a",
          "sha256": "e7a3fdb1fb8b05633d1132ae90fd8b4940018245ea029fc9a01c30c1fa21e002",
          "sha1": "e2e13f413354170952cea412748fcccd1a3d26b4",
          "md5": "5cee75000ae754e5f192083009e32279"
        }
      ]
    }
  ]
}
