{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-external",
    "version": "0.11.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "b2661a3ca4eedb2de37381342956f82f41d1bf4736fac8912b0c943a3e0e3e2dfa285755dc789f63292f6de8ac13572806be5484d5dc174ae31bfbe325e58f3f",
          "sha256": "8cd679603ec1d72d04353d33cac9bf202d5ccea93627f56f22c849b7304cd3a6",
          "sha1": "d04840aed436ad49ee6bbbcf646154a1eadf3bbb",
          "md5": "7d376afc1dabd5cf8d1ef74a2d751abf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup",
          "module": "gr8-plugin-common",
          "version": {
            "requires": "0.11.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "b2661a3ca4eedb2de37381342956f82f41d1bf4736fac8912b0c943a3e0e3e2dfa285755dc789f63292f6de8ac13572806be5484d5dc174ae31bfbe325e58f3f",
          "sha256": "8cd679603ec1d72d04353d33cac9bf202d5ccea93627f56f22c849b7304cd3a6",
          "sha1": "d04840aed436ad49ee6bbbcf646154a1eadf3bbb",
          "md5": "7d376afc1dabd5cf8d1ef74a2d751abf"
        }
      ]
    }
  ]
}
