{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-external",
    "version": "0.11.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "57ccbd55d64dfde0a26ab716f52b7854409a54a31828c828f17010c21089c6937d3aa403cd693730bb731305564ed04ff7b814a6e3c0f009678a80c990b7c5a1",
          "sha256": "10e9dfcefb7adc824baaa2a257001b313f9f52bb524cc4a7c7b8910826d55f55",
          "sha1": "964939729e08a1c2d1066a730fe8317a3ddfc73c",
          "md5": "0bb7807c20df3e6faa4512c6db20206c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup",
          "module": "gr8-plugin-common",
          "version": {
            "requires": "0.11.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "57ccbd55d64dfde0a26ab716f52b7854409a54a31828c828f17010c21089c6937d3aa403cd693730bb731305564ed04ff7b814a6e3c0f009678a80c990b7c5a1",
          "sha256": "10e9dfcefb7adc824baaa2a257001b313f9f52bb524cc4a7c7b8910826d55f55",
          "sha1": "964939729e08a1c2d1066a730fe8317a3ddfc73c",
          "md5": "0bb7807c20df3e6faa4512c6db20206c"
        }
      ]
    }
  ]
}
