{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-external",
    "version": "0.11.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "a241e97c35d76f2358eba5a16498217b985cbecf0b97b9cb0862ec934614534daffdc96bda37f9487787de42656452a6cdb736240437b5f9baeed67cf70e2653",
          "sha256": "2391bc4bfb52b39300b1e28a48aaf63d225ed0eb14986e9ea0825838429f6e04",
          "sha1": "c89ca11f68a18911d65efc72714a1760ef655560",
          "md5": "e54de724455e5f1776a5633b05e3a4bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup",
          "module": "gr8-plugin-common",
          "version": {
            "requires": "0.11.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "a241e97c35d76f2358eba5a16498217b985cbecf0b97b9cb0862ec934614534daffdc96bda37f9487787de42656452a6cdb736240437b5f9baeed67cf70e2653",
          "sha256": "2391bc4bfb52b39300b1e28a48aaf63d225ed0eb14986e9ea0825838429f6e04",
          "sha1": "c89ca11f68a18911d65efc72714a1760ef655560",
          "md5": "e54de724455e5f1776a5633b05e3a4bb"
        }
      ]
    }
  ]
}
