{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-external",
    "version": "0.11.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "6e6958bb12877fee5853a1bfd8a1e0b2f5a63bb9edd66935bca738361bbbc5747aa70cd782550cc09792b7639a645f4de693eb5386a80a57cd66fed2f79481ac",
          "sha256": "ced95ee2d5f1d9eb32584d710be2ca117f9d455f80c9627278898c95fccae08e",
          "sha1": "d322021666ffe6e498b9815875a91991b4be0d77",
          "md5": "317b8b748643fd620f4c904302f2807b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup",
          "module": "gr8-plugin-common",
          "version": {
            "requires": "0.11.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "6e6958bb12877fee5853a1bfd8a1e0b2f5a63bb9edd66935bca738361bbbc5747aa70cd782550cc09792b7639a645f4de693eb5386a80a57cd66fed2f79481ac",
          "sha256": "ced95ee2d5f1d9eb32584d710be2ca117f9d455f80c9627278898c95fccae08e",
          "sha1": "d322021666ffe6e498b9815875a91991b4be0d77",
          "md5": "317b8b748643fd620f4c904302f2807b"
        }
      ]
    }
  ]
}
