{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-external",
    "version": "0.11.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "644cb12b20449880f458e195065179e1b051d2a76ba645d73d4a55601e91d0b5d39db8bd5d67b841b2b4ecec9d1924ae7be2245c4746da612f9864e110ba4019",
          "sha256": "092b0cc8e346bb49150ee3d702ea2ad3ba491ce0da1a750fbbe2a069ff2e321d",
          "sha1": "a07080644d80637ad74c2494eede7da3728aacb5",
          "md5": "7de418b9d77e8a2f9f6619696d3e7bbc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup",
          "module": "gr8-plugin-common",
          "version": {
            "requires": "0.11.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "644cb12b20449880f458e195065179e1b051d2a76ba645d73d4a55601e91d0b5d39db8bd5d67b841b2b4ecec9d1924ae7be2245c4746da612f9864e110ba4019",
          "sha256": "092b0cc8e346bb49150ee3d702ea2ad3ba491ce0da1a750fbbe2a069ff2e321d",
          "sha1": "a07080644d80637ad74c2494eede7da3728aacb5",
          "md5": "7de418b9d77e8a2f9f6619696d3e7bbc"
        }
      ]
    }
  ]
}
