{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-external",
    "version": "0.11.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "6ac97bf94fa12bfcc7eb2119f097645feaaf6e09fb7ce61d01110eaf521081ebd2bfdae42a543221a6f23a5082cd67c018e327ecd20f77b4e2c9ceda8c33bdc7",
          "sha256": "af4271ffa620f89ce57e668a6cbeebc6524a2ad8d646100488d37dd2df856b89",
          "sha1": "594363a0f5ae903fa10f6acfd633dcb32f14f1e5",
          "md5": "bcc77fd6a219a97f5e834f11b215f44b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup",
          "module": "gr8-plugin-common",
          "version": {
            "requires": "0.11.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.11.3-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "6ac97bf94fa12bfcc7eb2119f097645feaaf6e09fb7ce61d01110eaf521081ebd2bfdae42a543221a6f23a5082cd67c018e327ecd20f77b4e2c9ceda8c33bdc7",
          "sha256": "af4271ffa620f89ce57e668a6cbeebc6524a2ad8d646100488d37dd2df856b89",
          "sha1": "594363a0f5ae903fa10f6acfd633dcb32f14f1e5",
          "md5": "bcc77fd6a219a97f5e834f11b215f44b"
        }
      ]
    }
  ]
}
