{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-common",
    "version": "0.11.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-common-0.11.2-SNAPSHOT.jar",
          "url": "gr8-plugin-common-0.11.2-SNAPSHOT.jar",
          "size": 34589,
          "sha512": "05515b136337b87add4a6cbc8672dd92af9924dfd3090d4cf51c086be3916d243cbe63fc34af91cd29b39a7f3629976338ce20d8933ab2a0936be6872817f604",
          "sha256": "dc280cdb69ea6def1b3a957fa9bd3aa9e28b18baf32673bf900007245587990f",
          "sha1": "03ae68bbca9d15c4491b434d19aa6720784b5311",
          "md5": "6be3d1912e521bf10a37e0aed34a0515"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-common-0.11.2-SNAPSHOT.jar",
          "url": "gr8-plugin-common-0.11.2-SNAPSHOT.jar",
          "size": 34589,
          "sha512": "05515b136337b87add4a6cbc8672dd92af9924dfd3090d4cf51c086be3916d243cbe63fc34af91cd29b39a7f3629976338ce20d8933ab2a0936be6872817f604",
          "sha256": "dc280cdb69ea6def1b3a957fa9bd3aa9e28b18baf32673bf900007245587990f",
          "sha1": "03ae68bbca9d15c4491b434d19aa6720784b5311",
          "md5": "6be3d1912e521bf10a37e0aed34a0515"
        }
      ]
    }
  ]
}
