{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-external",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.0.jar",
          "url": "gr8-plugin-external-0.11.0.jar",
          "size": 2052,
          "sha512": "1a4940d0e0ba4945116106c204caa7d4d463bd734453ffe6fac593f193dae9617ac5f264fe9eae63d488b08431b21f27ca755b0cfae574fdda05d718993664bb",
          "sha256": "e89b0bd04c3398b4ea02fecc31ddabe7644902cbe2b463788afa15a7c96c5377",
          "sha1": "4e2ed361ad9d21df8f5a384fb491217234abc509",
          "md5": "6ead5487d649f0ebf467eb76c77bff5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup",
          "module": "gr8-plugin-common",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.0.jar",
          "url": "gr8-plugin-external-0.11.0.jar",
          "size": 2052,
          "sha512": "1a4940d0e0ba4945116106c204caa7d4d463bd734453ffe6fac593f193dae9617ac5f264fe9eae63d488b08431b21f27ca755b0cfae574fdda05d718993664bb",
          "sha256": "e89b0bd04c3398b4ea02fecc31ddabe7644902cbe2b463788afa15a7c96c5377",
          "sha1": "4e2ed361ad9d21df8f5a384fb491217234abc509",
          "md5": "6ead5487d649f0ebf467eb76c77bff5a"
        }
      ]
    }
  ]
}
