{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-external",
    "version": "0.10.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.10.1-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.10.1-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "5099e5d894c012298563779363f55e38477e31c522aadfa5d532ec994b6ac900d8a512f72aee400ddcf5f6b87817ee388179bf8b4bf6355f87c10ad80a1c5b15",
          "sha256": "b99c2cba773b660bfb96246c5d303dcaae52de58894c768087c77b3b2a1a1a27",
          "sha1": "bc162d227eb44e5a1b65064b3f99aa9978ab319d",
          "md5": "1c001b134251c5f71d389378d7f1b17a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup",
          "module": "gr8-plugin-common",
          "version": {
            "requires": "0.10.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.10.1-SNAPSHOT.jar",
          "url": "gr8-plugin-external-0.10.1-SNAPSHOT.jar",
          "size": 2052,
          "sha512": "5099e5d894c012298563779363f55e38477e31c522aadfa5d532ec994b6ac900d8a512f72aee400ddcf5f6b87817ee388179bf8b4bf6355f87c10ad80a1c5b15",
          "sha256": "b99c2cba773b660bfb96246c5d303dcaae52de58894c768087c77b3b2a1a1a27",
          "sha1": "bc162d227eb44e5a1b65064b3f99aa9978ab319d",
          "md5": "1c001b134251c5f71d389378d7f1b17a"
        }
      ]
    }
  ]
}
