{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin",
    "version": "0.11.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-0.11.3-SNAPSHOT.jar",
          "size": 295672,
          "sha512": "7d1effdf99f9926c3f170fbab58cc31f428c549cb90f2c85d5660e02c7cf5c610b212fc1bf6c28fe2413f4cd2acba006be397188979e77722bc7f69a873c5498",
          "sha256": "528eb247a5025de130d37d35540ab2cf694a1d7e9bd4e8035322e04a1b129aaa",
          "sha1": "b310cc0f29e9c5bbfbc4123d479c550cb3f2fd38",
          "md5": "04ab391a12af94b199fdad1ef0493df5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup",
          "module": "gr8-plugin-common",
          "version": {
            "requires": "0.11.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-0.11.3-SNAPSHOT.jar",
          "size": 295672,
          "sha512": "7d1effdf99f9926c3f170fbab58cc31f428c549cb90f2c85d5660e02c7cf5c610b212fc1bf6c28fe2413f4cd2acba006be397188979e77722bc7f69a873c5498",
          "sha256": "528eb247a5025de130d37d35540ab2cf694a1d7e9bd4e8035322e04a1b129aaa",
          "sha1": "b310cc0f29e9c5bbfbc4123d479c550cb3f2fd38",
          "md5": "04ab391a12af94b199fdad1ef0493df5"
        }
      ]
    }
  ]
}
