{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin",
    "version": "0.11.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-0.11.3-SNAPSHOT.jar",
          "size": 295788,
          "sha512": "5f1078893e1f7d6a2a2929fe2a64de9ff66a92ca0e1e4aca1dd0664ca1f8bfa6539e65561d79c7319d0410a7654a4177389cd9b3985aa9eab6c37ac263b814be",
          "sha256": "c7c0fde1aece77e395ea38717e97d1fe4cfab9b269d65fb039078dde3103604c",
          "sha1": "709025362983c689fef12d512ce15ce8bf618d70",
          "md5": "73c854d0dbf53f803a6e54902ea3b394"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup",
          "module": "gr8-plugin-common",
          "version": {
            "requires": "0.11.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-0.11.3-SNAPSHOT.jar",
          "size": 295788,
          "sha512": "5f1078893e1f7d6a2a2929fe2a64de9ff66a92ca0e1e4aca1dd0664ca1f8bfa6539e65561d79c7319d0410a7654a4177389cd9b3985aa9eab6c37ac263b814be",
          "sha256": "c7c0fde1aece77e395ea38717e97d1fe4cfab9b269d65fb039078dde3103604c",
          "sha1": "709025362983c689fef12d512ce15ce8bf618d70",
          "md5": "73c854d0dbf53f803a6e54902ea3b394"
        }
      ]
    }
  ]
}
