{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-common",
    "version": "0.11.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-common-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-common-0.11.3-SNAPSHOT.jar",
          "size": 34589,
          "sha512": "d2c0cca318c0643e5242a8f5df676a4a33d469481c885f7ba38344f2542355172dde8b8f123515a92933ed14d414ad96b08064d24d46a1545edb5656c287d619",
          "sha256": "ded5c316356e9f3cb3dfff3fe0eee65e56889162102781dfd3d9623888cd86ad",
          "sha1": "8b12655135c14fb1123a001bce5a4de732c615bd",
          "md5": "9b378b89afc305f4e0805710d023c947"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-common-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-common-0.11.3-SNAPSHOT.jar",
          "size": 34589,
          "sha512": "d2c0cca318c0643e5242a8f5df676a4a33d469481c885f7ba38344f2542355172dde8b8f123515a92933ed14d414ad96b08064d24d46a1545edb5656c287d619",
          "sha256": "ded5c316356e9f3cb3dfff3fe0eee65e56889162102781dfd3d9623888cd86ad",
          "sha1": "8b12655135c14fb1123a001bce5a4de732c615bd",
          "md5": "9b378b89afc305f4e0805710d023c947"
        }
      ]
    }
  ]
}
