{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-common",
    "version": "0.11.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-common-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-common-0.11.3-SNAPSHOT.jar",
          "size": 34492,
          "sha512": "7e807f6aaf61328e849e1eaf5dcad1e49a80473cbc602d34b5e7de96d9043ae1a605329190933f9ff909686d9ba95e1aba7534e0323fb0bb80e2c94a59894e55",
          "sha256": "56a4e77cfeece7987702d6980e881ef6baf1d5df7299987045b8558270e3dd09",
          "sha1": "ebef03f06ba4cd3d77a6c2859b8a9f19851c5d0a",
          "md5": "c7644f54d4168061d67e45450ee739dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-common-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-common-0.11.3-SNAPSHOT.jar",
          "size": 34492,
          "sha512": "7e807f6aaf61328e849e1eaf5dcad1e49a80473cbc602d34b5e7de96d9043ae1a605329190933f9ff909686d9ba95e1aba7534e0323fb0bb80e2c94a59894e55",
          "sha256": "56a4e77cfeece7987702d6980e881ef6baf1d5df7299987045b8558270e3dd09",
          "sha1": "ebef03f06ba4cd3d77a6c2859b8a9f19851c5d0a",
          "md5": "c7644f54d4168061d67e45450ee739dc"
        }
      ]
    }
  ]
}
