{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-common",
    "version": "0.11.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-common-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-common-0.11.3-SNAPSHOT.jar",
          "size": 34589,
          "sha512": "bd922049d34d7dc5867f68e72aeae81f00b5721ba2aa1ed5f59695cb565a9833b4f788d3d568c4be1cb67077616e61163067d8080d9963f7dd159a9bd7aaacc7",
          "sha256": "c07736ff0358862c1551c67cbc0548069b83f6c13b800d16b68750ed07a195bb",
          "sha1": "613f6f4f7a59d4d30bb94e76938c8ef7337a6e57",
          "md5": "1de19d22bcecba0f7441d3ba38f8352a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-common-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-common-0.11.3-SNAPSHOT.jar",
          "size": 34589,
          "sha512": "bd922049d34d7dc5867f68e72aeae81f00b5721ba2aa1ed5f59695cb565a9833b4f788d3d568c4be1cb67077616e61163067d8080d9963f7dd159a9bd7aaacc7",
          "sha256": "c07736ff0358862c1551c67cbc0548069b83f6c13b800d16b68750ed07a195bb",
          "sha1": "613f6f4f7a59d4d30bb94e76938c8ef7337a6e57",
          "md5": "1de19d22bcecba0f7441d3ba38f8352a"
        }
      ]
    }
  ]
}
