{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-common",
    "version": "0.11.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-common-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-common-0.11.3-SNAPSHOT.jar",
          "size": 34589,
          "sha512": "85f63c23b362872f63d0b819ea53faf9151b57f6a05262266d372138a3ad7a00f819087b48803de80be191372313df6ae1ed04073e1449dd64297270ded00432",
          "sha256": "53932df22cba4aaf59dc5094746fd705a62e446ca09274e5444fbf6f27cc4989",
          "sha1": "5354347bc0344b0280f0607d63a9a5da5c091a4d",
          "md5": "dd2dd6e03b6f2bfa78fbdb0f8ebb9c7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-common-0.11.3-SNAPSHOT.jar",
          "url": "gr8-plugin-common-0.11.3-SNAPSHOT.jar",
          "size": 34589,
          "sha512": "85f63c23b362872f63d0b819ea53faf9151b57f6a05262266d372138a3ad7a00f819087b48803de80be191372313df6ae1ed04073e1449dd64297270ded00432",
          "sha256": "53932df22cba4aaf59dc5094746fd705a62e446ca09274e5444fbf6f27cc4989",
          "sha1": "5354347bc0344b0280f0607d63a9a5da5c091a4d",
          "md5": "dd2dd6e03b6f2bfa78fbdb0f8ebb9c7e"
        }
      ]
    }
  ]
}
