{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-external",
    "version": "0.11.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.2.jar",
          "url": "gr8-plugin-external-0.11.2.jar",
          "size": 2052,
          "sha512": "0dfc0ef0713a305e156d6d48b7f8b1985d670a00822aac9082f562b096d7d3f1ee4a8eb002533705bc1515f113ff2a16eb7eb984dbb338682c53624d02849736",
          "sha256": "f0b0bca585aa12f23a4cc22f6e9e70ddb6a256ad4d085207250b28c547b8ad11",
          "sha1": "e16eb150e154968d0f79338369f5dc5a88293252",
          "md5": "a9609fe6f3c6853b8491f78e5228c5ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup",
          "module": "gr8-plugin-common",
          "version": {
            "requires": "0.11.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-external-0.11.2.jar",
          "url": "gr8-plugin-external-0.11.2.jar",
          "size": 2052,
          "sha512": "0dfc0ef0713a305e156d6d48b7f8b1985d670a00822aac9082f562b096d7d3f1ee4a8eb002533705bc1515f113ff2a16eb7eb984dbb338682c53624d02849736",
          "sha256": "f0b0bca585aa12f23a4cc22f6e9e70ddb6a256ad4d085207250b28c547b8ad11",
          "sha1": "e16eb150e154968d0f79338369f5dc5a88293252",
          "md5": "a9609fe6f3c6853b8491f78e5228c5ca"
        }
      ]
    }
  ]
}
