{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup",
    "module": "gr8-plugin-common",
    "version": "0.11.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-common-0.11.2.jar",
          "url": "gr8-plugin-common-0.11.2.jar",
          "size": 34589,
          "sha512": "861d485736311fdb88241e5f4baadaa087b6e47a8ac9fe55fa1d27920f2ee9efd48740895e75e9ab4e428afefb512a2cd955ce4f05ffba920aa0c1fc8e6a9e9e",
          "sha256": "d10c18ba767e772f2c0ddfebbbf8d42775bd33313c329eadc0d64103e7572992",
          "sha1": "851630133d758620356b64071568cba32c8eeda3",
          "md5": "c7e2daf1e6ad5b2bc7ff0f65af131861"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gr8-plugin-common-0.11.2.jar",
          "url": "gr8-plugin-common-0.11.2.jar",
          "size": 34589,
          "sha512": "861d485736311fdb88241e5f4baadaa087b6e47a8ac9fe55fa1d27920f2ee9efd48740895e75e9ab4e428afefb512a2cd955ce4f05ffba920aa0c1fc8e6a9e9e",
          "sha256": "d10c18ba767e772f2c0ddfebbbf8d42775bd33313c329eadc0d64103e7572992",
          "sha1": "851630133d758620356b64071568cba32c8eeda3",
          "md5": "c7e2daf1e6ad5b2bc7ff0f65af131861"
        }
      ]
    }
  ]
}
